@echo off
REM Render service (AI-Youtube-Shorts-Generator fork) - hybrid shorts renderer.
REM Runs the FastAPI service on port 8084 (host loopback only).
REM Autostart via Windows Scheduled Task: AelfLab_RenderService

cd /d D:\homelab\hermes-workspace\AI-Youtube-Shorts-Generator
set RENDER_PORT=8084
set RENDER_OUTPUT_DIR=D:\homelab\hermes-workspace\AI-Youtube-Shorts-Generator\rendered
set RENDER_PATH_PREFIX=short
set RENDER_FACE_ZOOM=0.85
set RENDER_FORMAT=2160
set RENDER_OUTPUT_WIDTH=1080
set RENDER_OUTPUT_HEIGHT=1920
set HF_HUB_OFFLINE=1
set PYTHONIOENCODING=utf-8
set RENDER_DEBUG_TRACK=1
set RENDER_SPLIT=1
set RENDER_SPLIT_FADE_S=0.3
set RENDER_SPLIT_HOLD_S=2.5
set RENDER_SPLIT_MOUTH_DELTA=0.15
set RENDER_SPLIT_SINGLE_S=0.45

REM ── Phase 1 (Correctness): persistent tracking + focus hysteresis ──
set RENDER_FACE_MATCH_DISTANCE=1.65
set RENDER_TRACK_ASSIGNMENT_MARGIN=0.12
set RENDER_FACE_TRACK_TTL_S=0.45
set RENDER_FACE_BOX_EMA=0.28
set RENDER_FOCUS_SWITCH_CONFIRM_S=0.55
set RENDER_FOCUS_MIN_HOLD_S=1.20
set RENDER_FOCUS_SCORE_MARGIN=0.18
set RENDER_FOCUS_LOST_GRACE_S=0.60
set RENDER_FOCUS_MIN_CONFIDENCE=0.58
set RENDER_SCENE_CHANGE_THRESHOLD=0.55

REM ── Phase 2 (Stability): smooth camera + split lock + temporal reaction ──
set RENDER_CAMERA_POSITION_SMOOTH_S=0.32
set RENDER_CAMERA_ZOOM_SMOOTH_S=0.45
set RENDER_CAMERA_MAX_PAN_PER_S=0.85
set RENDER_CAMERA_MAX_ZOOM_PER_S=0.65
set RENDER_CAMERA_DEADZONE_X=0.025
set RENDER_CAMERA_DEADZONE_Y=0.020
set RENDER_SPLIT_REACT_ACTIVITY=2.4
set RENDER_SPLIT_REACT_DELTA=0.8

REM ── Phase 3/4 (Quality+Polish): captions, punch-in, layouts, QC ──
set RENDER_CAPTION_MAX_LINES=2
set RENDER_CAPTION_MAX_WORDS=6
set RENDER_CAPTION_MIN_WORDS=2
set RENDER_CAPTION_FACE_AVOIDANCE=1
set RENDER_EMPHASIS_ZOOM_MAX=1.10
set RENDER_EMPHASIS_MIN_INTERVAL_S=4.0
set RENDER_EMPHASIS_DURATION_S=0.65
set RENDER_COLOR_CORRECTION=1
set RENDER_OUTPUT_SHARPEN=0.12
set RENDER_CROP_QUALITY_MIN_SCORE=60
set RENDER_VIDEO_CRF=17
set RENDER_VIDEO_PRESET=slow
set RENDER_QC_MIN_SCORE=80
set RENDER_QC_BLOCK_UPLOAD=1

".venv\Scripts\python.exe" render_service.py >> D:\homelab\hermes-workspace\AI-Youtube-Shorts-Generator\render-service.log 2>&1
