"""Phase 2 (Visual regression) — deterministic fixture tests.

Renders the synthetic fixture clips through the real clipper pipeline and
asserts the QC/tracking artifacts are produced without crashing and match
sanity bounds. Fixtures live in fixtures/visual/*.mp4 (generated by
scripts/make_visual_fixtures.py — deterministic, no YouTube needed).

Run with:
    .venv/Scripts/python.exe -m pytest test_visual_regression.py -q

NOTE: full-frame tracking on 720p takes a few seconds per clip; we run the
smoke render on single_speaker only and validate the OTHER fixtures'
metadata (existence + duration + dimension) so the suite stays fast.
"""
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import cv2

FIXTURES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures", "visual")
EXPECTED_SCENARIOS = [
    "single_speaker",
    "dual_speaker",
    "switch",
    "reaction",
    "low_light",
    "screen_share",
    "missed_face",
    "hard_cut",
]


def _probe(path: str):
    cap = cv2.VideoCapture(path)
    if not cap.isOpened():
        return None
    fps = cap.get(cv2.CAP_PROP_FPS)
    frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    cap.release()
    return {"fps": fps, "frames": frames, "width": width, "height": height}


class TestVisualFixtures(unittest.TestCase):
    def test_all_scenarios_exist_and_are_valid_video(self):
        for name in EXPECTED_SCENARIOS:
            path = os.path.join(FIXTURES_DIR, f"{name}.mp4")
            with self.subTest(scenario=name):
                self.assertTrue(os.path.exists(path), f"missing fixture {path}")
                info = _probe(path)
                self.assertIsNotNone(info, f"cannot open {path}")
                self.assertGreaterEqual(info["frames"], 100)
                self.assertEqual((info["width"], info["height"]), (1280, 720))

    def test_fixtures_have_expected_variation(self):
        """Fixtures must actually DIFFER from each other (regression guard
        against a generator that writes identical frames everywhere)."""
        import numpy as np

        def mean_frame(path: str):
            cap = cv2.VideoCapture(path)
            ok, frame = cap.read()
            cap.release()
            return frame.mean() if ok else None

        means = {name: mean_frame(os.path.join(FIXTURES_DIR, f"{name}.mp4")) for name in EXPECTED_SCENARIOS}
        # Screen share is bright; low light is dark — they must be far apart.
        self.assertGreater(means["screen_share"], means["low_light"] + 20)

    def test_single_speaker_renders_through_clipper(self):
        """Smoke: crop+reframe the single_speaker fixture with a timeline
        artifact; assert the output exists and QC stats are produced."""
        from shorts_generator.local import clipper

        src = os.path.join(FIXTURES_DIR, "single_speaker.mp4")
        out = os.path.join(FIXTURES_DIR, "_smoke_out.mp4")
        try:
            result = clipper.crop_clip_local(
                src, 0.0, 2.0, "9:16", out,
                final_encode=False,
                layout_mode="face_crop",
                return_timeline=True,
            )
            self.assertIsInstance(result, tuple)
            path, timeline = result
            self.assertTrue(os.path.exists(path), f"output missing: {path}")
            self.assertIn("frames", timeline.stats)
            # Reframed output must be vertical.
            info = _probe(path)
            if info:
                self.assertGreater(info["height"], info["width"])
        finally:
            for suffix in ("", ".cut.mp4", ".silent.mkv"):
                p = out + suffix
                if os.path.exists(p):
                    try:
                        os.remove(p)
                    except PermissionError:
                        pass


if __name__ == "__main__":
    unittest.main(verbosity=2)
